name: CI

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: Build
        run: docker build . -t mydjango:latest

      - name: Testing
        run: docker run mydjango:latest pytest

      - name : Push image
        run: kind load docker-image mydjango:latest --name "chart-testing"

      - name: Deploy on kube
        run: |
          kubectl apply -f kubefiles/
          kubectl get pods
          kubectl get services
          sleep 60
          kubectl port-forward service/django 8000:8000 &

      - name: Check Homepage
        run: curl localhost:8000/healthz