name: CI

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: Build
        run: |
          docker build . -t mydjango:$GITHUB_SHA
          kind load docker-image mydjango:$GITHUB_SHA --name "chart-testing"

      - name: Deploy on kube
        run: kubectl apply -f kubefiles/
      
      - name: Some sleep...
        run: |
          sleep 15
          kubectl get pods
          kubectl get services

      - name: Get some logs
        run: kubectl logs -l name=django

      - name: Check Homepage
        run: curl localhost:8000