name: CI

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: Docker Hub Login
        run: docker login -u csepulvedab -p ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build
        run: docker build . -t csepulvedab/mydjango:latest

      - name: Testing
        run: docker run csepulvedab/mydjango:latest pytest

      - name : Push image
        run: |
          docker login -u csepulvedab -p ${{ secrets.DOCKERHUB_PASSWD }}
          docker push csepulvedab/mydjango:latest

      - name: Deploy on kube
        run: |
          kubectl apply -f kubefiles/
          kubectl get pods
          kubectl get services
          kubectl wait --for=condition=ready pod --all --timeout=60s
          kubectl port-forward service/django 8000:8000 &

      - name: Check Homepage
        run: curl localhost:8000/healthz