name: CI

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: Build
        run: docker build . -t mydjango

      - name: Deploy on kube
        run: kubectl apply -f kubefiles/
      
      - name: some sleep...
        run: sleep 30

      - name: Get some logs
        run: kubectl logs -l name=django

      - name: Check Homepage
        run: curl localhost:8000